project:
  type: website

website:
  title: "Marianna Rosso"
  sidebar:
    style: "docked"
    search: false
    background: "black"
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - portfolio.qmd
      - cv.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual
execute:
  freeze: auto