---
title: "Publications"
---

Zurrer WE, Cannon AE, Ewing E, **Rosso M**, Reich DS, Ineichen BV (2023). "*Auto-STEED: A data mining tool for automated extraction of experimental paramenters and risk of bias items from in-vivo publications.*" BioRxiv, [doi](https://doi.org/10.1101/2023.02.24.529867)

Novak J, Jaric I, **Rosso M**, Rufener R, Touma C, Würbel H (2022) "*Handling method affects measures of anxiety, but not chronic stress in mice*." Scientific Reports, [doi](https://doi.org/10.1038/s41598-022-25090-9)

**Rosso M**, Herrera A, Würbel H, Voelkl B (2022) "*Evidence for HARKing in mouse behavioural test of anxiety*." bioRxiv, [doi](https://doi.org/10.1101%2F2022.12.01.518668)

**Rosso M**, Wirz R, Loretan AV, Sutter NA, da Cunha CTP, Jaric I, Würbel H, Voelkl B (2022). "*Reliability of common mouse behavioural tests of anxiety: A systematic review and meta-analysis on the effects of anxiolytics*." Neuroscience and Biobehavioral Reviews, [doi](https://doi.org/10.1016/j.neubiorev.2022.104928)

Jaric I, Voelkl B, Clerc M, Schmid MW, Novak J, **Rosso M,** Rufener R, von Kortzfleisch VT, Richter SH, Buettner M, Bleich A, Amrein I, Wolfer DP, Touma C, Sunagawa S, Würbel H (2022). "*The rearing environment persistently modulates mouse phenotypes from the molecular to the behavioural level.*" PLOS Biology, [doi](https://doi.org/10.1371/journal.pbio.3001837)

von Kortzfleisch VT, Ambrée O, Karp NA, Meyer N, Novak J, Palme R, **Rosso M**, Touma C, Würbel H, Kaiser S, Sachser N, Richter SH (2022). "*Do multiple experimenters improve the reproducibility of animal studies?*" PLOS Biology, [doi](https://doi.org/10.1371/journal.pbio.3001564)

Jaric I, Voelkl B, Clerc M, Schmid MW, Novak J, **Rosso M**, Rufener R, von Kortzfleisch V, Richter HS, Buettner M, Bleich A, Amrein I, Wolfer DP, Touma C, Sunagawa S, Wuerbel H (2022). "*Rearing environment persistently modulates the phenotype of mice.*" bioRxiv, [doi](https://doi.org/10.1101/2022.02.11.480070)

Bailoo JD, Voelkl B, Varholick J, Novak J, Murphy E, **Rosso M**, Palme R, Würbel H (2020). "*Effects of weaning age and housing conditions on phenotypic differences in mice.*" Scientific Reports, [doi](https://doi.org/10.1038/s41598-020-68549-3)
